syntax = "proto3";
package dv_msgs;
import "base_msgs.proto";

/**
 * Driverless cones proto message. Primarily used to package ground-truth cone positions from the simulator to Drivebrain itself.
*/
message Cones {
  enum ConeColor { UNKNOWN = 0; BLUE = 1; YELLOW = 2; ORANGE_SMALL = 3; ORANGE_BIG = 4 ; }
  message Cone { hytech_msgs.xyz_vector position = 1; ConeColor color = 2; }
  repeated Cone cones = 1;
  uint64 timestamp_us = 2;
}

message SimulationGroundTruth {
  uint64 timestamp_ns = 1;

  double x_world_m = 2;
  double y_world_m = 3;
  double yaw_world_rad = 4;

  double vx_world_mps = 5;
  double vy_world_mps = 6;
  double yaw_rate_radps = 7;

  double ax_world_mps2 = 8;
  double ay_world_mps2 = 9;
  double yaw_accel_radps2 = 10;
}
