name: Generate and Release

on:
  repository_dispatch

jobs:
  build-lib:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [23.11]

    steps:
      - name: Test Send JSON
        run: 'python3 test.py "${{ github.event.client_payload }}"'


