name: Generate and Release

on:
  repository_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [23.11]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: LS
        run: 'ls'

      - name: Test Send JSON
        run: 'echo "Received JSON: ${{ toJson(github.event.client_payload) }}"'


